extends: MH0386
queue_rules:
  - name: default
    queue_conditions:
      - and:
          - author != MH0386
          - check-success = Build and publish AUR Package
          - check-success = prek
          - 'check-success = DeepSource: Secrets'
          - 'check-success = DeepSource: Shell'
          - check-success = CodeFactor
          - check-success = GitGuardian Security Checks
          - check-success = CodeQL
    autoqueue: true
merge_protections_settings:
  reporting_method: check-runs
