name: GitHub Agentic Workflows Compile
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  push:
    paths:
      - .github/workflows/**.md
permissions:
  contents: write
jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Install GH AW CLI
        uses: github/gh-aw-actions/setup-cli@3928d9c902852a519b0a03ea19f4fe43c085c753 # v0.77.6
      - name: Compile
        run: gh aw compile
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: Compile GH AW
          commit_options: --no-verify
          push_options: --force
          file_pattern: .github/workflows/**.lock.yml
